Change scripts to conform to edge-conventions
Exception: npm run precommit will not run `test` which has to access actual electrum servers and could fail due to network issues